-- DROP DATABASE
DROP DATABASE IF EXISTS ecommerce_db;

-- CREATE DATABASE
CREATE DATABASE ecommerce_db;


USE ecommerce_db;

CREATE TABLE category (
    id INT NOT NULL AUTO AUTO_INCREMENT
    category_name VARCHAR(30) NOT NULL,
)

